name: flutter_application_1
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0
environment:
  sdk: '>=3.3.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  carousel_slider: ^4.2.1
  cupertino_icons: ^1.0.6
  supabase_flutter: ^2.0.0
  dio: ^5.4.1
  flutter_bloc: ^8.1.4
  email_validator: ^2.1.17
  file_picker: ^8.0.0+1
  #open_file: ^3.3.2
  just_audio: ^0.9.36





dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
flutter:
  uses-material-design: true
  fonts:
    - family: iransans
      fonts:
        - asset: assets/fonts/IranianSans.ttf
         